### ISSUE TITLE
Example of config for this authservice together with KeyCloak as OIDC Provider?

### ISSUE THREAD

**Issue by bruegth** [istio-ecosystem/authservice#99]
It is possible to get an example of config for envoy together with Keycloak as OIDC Provider?

**Comment by cfryanr** [comment]
I don't think we want to provide specific examples for each kind of OIDC Identity Provider, since there are so many. Is there something specific that you're having trouble with, @bruegth?

For example, perhaps we need an example of how to set up Authservice when your OIDC Identity Provider is running in the same service mesh (same K8s cluster) as the apps that it is protecting.

**Comment by bruegth** [comment]
No worries, I will try to configure KeyCloak & authservice by my own. I will report back if I ran into Problems.

Thanks.

**Comment by zimmertr** [comment]
I would have found this useful today. :)
